nameOverride: ""
fullnameOverride: ""

namespace:
  create: true
  name: demo-app

replicaCount: 2

image:
  repository: nginx
  tag: "1.25"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 8080
  targetPort: 80
  nodePort: 30080

resources:
  requests:
    cpu: 100m
    memory: 64Mi
  limits:
    cpu: 250m
    memory: 128Mi
